services:
  - type: web
    name: gongcanglian-test
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: AUTH_SECRET
        generateValue: true
